### ISSUE TITLE
Compare pre- vs post- curriculum overhaul?

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/assessment#12]
_From @karenword on March 1, 2018 20:38_

It would be great to know how or whether any of the changes that were made had an impact on outcomes! 

_Copied from original issue: carpentries/assessment#159_

**Comment by fmichonneau** [comment]
_From @karenword on March 1, 2018 20:39_

(re instructor training in particular, but conceptually applies to all curricula after a substantial change)

**Comment by kariljordan** [comment]
This would be a great way to focus the assessment reports in January. Adding it to our meeting notes @fmichonneau.

**Comment by kariljordan** [comment]
I met with @karenword about this issue. She would like to compare the responses of the instructor training surveys, not the learner surveys. We decided that looking at the overall results over time would be a good idea, and then we could identify outliers and point to what was happening during that time with the curriculum, etc. I shared our notes with @ErinBecker as I believe she's working on the programmatic (instructor training) reports in Q1 2020.

**Comment by ErinBecker** [comment]
Thanks @kariljordan  and @karenword - yes, this is going to be included in the Instructor Training report for Q1 2020 (and subsequently). I have [a plan laid out](https://docs.google.com/document/d/1dOZ7XnafKshSbe53fIAZZRlY5_OhY1MHXhCKwzhPU4U/edit) for data and analyses that will go into this report and will add discussion of this to my next meeting with @karenword.
