### ISSUE TITLE
Diagonal of Matrix of Common Tools Covered

### ISSUE THREAD

**Issue by rgaiacs** [carpentries/assessment#122]
On https://carpentries.github.io/assessment/carpentries/long-term-survey/report.html, the Matrix of Common Tools Covered should have the main diagonal with a blank value.

**Comment by kariljordan** [comment]
Thanks @rgaiacs! Do you know how to fix this? You can submit a PR if it's easier for you.

**Comment by rgaiacs** [comment]
From https://stat.ethz.ch/R-manual/R-devel/library/base/html/diag.html

~~~
> m2
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    5    9   13   17
[2,]    0    6   10   14   18
[3,]    0    0   11   15   19
[4,]    0    0    0   16   20
> diag(m2) <- 0
> m2
     [,1] [,2] [,3] [,4] [,5]
[1,]    0    5    9   13   17
[2,]    0    0   10   14   18
[3,]    0    0    0   15   19
[4,]    0    0    0    0   20
~~~

**Comment by machow** [comment]
The main diagonal is the number of times a course was taught, which you need to able to interpret the other numbers in a row! For example, cloud computing was only taught a few times (11), but almost half those times it was taught with Python (6).

If you want to know how often a how often tools co-occur, without regard to how popular a particular tool is, then you can divide each row by it's diagonal. So in the case above, dividing #python / #cloud_computing gives about .5.

**Comment by kariljordan** [comment]
@machow would you happen to have time to submit a PR to make this adjustment?

**Comment by kariljordan** [comment]
I just re-read @machow comment on this issue and it looks like the matrix can remain as is.
