### ISSUE TITLE
Lower half of Matrix of Common Tools Covered

### ISSUE THREAD

**Issue by rgaiacs** [carpentries/assessment#123]
On https://carpentries.github.io/assessment/carpentries/long-term-survey/report.html, the Matrix of Common Tools Covered is symmetric so we could drop the lower half.

**Comment by kariljordan** [comment]
@rgaiacs is there a fast way to fix this?

**Comment by kariljordan** [comment]
Closed per [this issue](https://github.com/carpentries/assessment/issues/122)
