### ISSUE TITLE
More organization of the assessment repo

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/assessment#136]
@kariljordan It would be good to be able to include programmatic assessment work that @maneesha  is doing in this repo as well. Could you please:

- put everything that’s currently in there (except for the assessment-network folder) into a folder called “learner-assessment”
- add a folder for Maneesha to work in called “programmatic- assessment”

**Comment by kariljordan** [comment]
@maneesha [programmatic-assessment](https://github.com/carpentries/assessment/tree/master/programmatic-assessment) has been added 

cc @ErinBecker

**Comment by kariljordan** [comment]
@tracykteal background for the programmatic-assessment folder in this repo.
