### ISSUE TITLE
Data for 'recommending a data carpentry workshop' isn't appearing

### ISSUE THREAD

**Issue by tracykteal** [carpentries/assessment#139]
In the Jan 2018 report, the data for 'recommending a data carpentry workshop' isn't appearing.

**Comment by tracykteal** [comment]
https://carpentries.github.io/assessment/learner-assessment/data-carpentry/postworkshop/2018-January/report.html

**Comment by kariljordan** [comment]
I had an [issue](https://github.com/carpentries/assessment/issues/133) figuring out how to represent this in the report because it was a slider scale question. I had a few suggestions, but hadn't circled back. Let me try to add it now.

**Comment by kariljordan** [comment]
Here is a table for now. They had to slide a scale from 0 to 100:

Recommend | n | %
-- | -- | --
0 | 2 | 0.8
20 | 1 | 0.4
23 | 1 | 0.4
26 | 1 | 0.4
30 | 1 | 0.4
35 | 1 | 0.4
50 | 3 | 1.2
57 | 1 | 0.4
60 | 1 | 0.4
61 | 1 | 0.4
64 | 1 | 0.4
65 | 5 | 2.0
68 | 1 | 0.4
69 | 1 | 0.4
70 | 4 | 1.6
71 | 1 | 0.4
72 | 1 | 0.4
73 | 1 | 0.4
75 | 8 | 3.1
76 | 3 | 1.2
77 | 3 | 1.2
78 | 3 | 1.2
79 | 3 | 1.2
80 | 8 | 3.1
81 | 1 | 0.4
82 | 2 | 0.8
83 | 4 | 1.6
85 | 10 | 3.9
86 | 2 | 0.8
87 | 1 | 0.4
88 | 3 | 1.2
89 | 2 | 0.8
90 | 26 | 10.2
91 | 1 | 0.4
92 | 3 | 1.2
93 | 3 | 1.2
94 | 2 | 0.8
95 | 13 | 5.1
96 | 3 | 1.2
97 | 2 | 0.8
98 | 5 | 2.0
99 | 8 | 3.1
100 | 107 | 42.1

I am working on a better way to show this now, don't worry. Just wanted you to have **something!**

**Comment by tracykteal** [comment]
Thanks! Should we change the question so it's easier to represent?

**Comment by tracykteal** [comment]
I like being able to say XX% percent of workshop participants agree or strongly agree that they would recommend this workshop to a friend or colleague. 

This question comes from the [Net Promoter Score](https://en.wikipedia.org/wiki/Net_Promoter) concept, so we can look there for how people ask and gather responses to this question. Because it is somewhat standard, being able to report it the same way would be useful too.

**Comment by kariljordan** [comment]
Yes, when we were developing the survey @JasonJWilliamsNY recommending using the net promoter score and we agreed it was standard. I found the [NPS package](https://cran.r-project.org/web/packages/NPS/NPS.pdf), so I'll take a look because the [beeswarm](https://carpentries.github.io/assessment/learner-assessment/data-carpentry/postworkshop/2018-January/2018-January-post.html) isn't giving me what I want.

**Comment by kariljordan** [comment]
The scoring for this question is based on a 0 to 100 scale. 
0 to 60: *Detractors*
90 to 100: *Promoters*
70 to 80: *Passives*

I want a table showing the percentage for each category.

This line of code:

```
data %>% 
  tally_and_perc(`Recommend`, na.rm = TRUE) %>% 
  kable()
```

gives me this table:

Recommend | n | %
-- | -- | --
0 | 2 | 0.8
20 | 1 | 0.4
23 | 1 | 0.4
26 | 1 | 0.4
30 | 1 | 0.4
35 | 1 | 0.4
50 | 3 | 1.2
57 | 1 | 0.4
60 | 1 | 0.4
61 | 1 | 0.4
64 | 1 | 0.4
65 | 5 | 2.0
68 | 1 | 0.4
69 | 1 | 0.4
70 | 4 | 1.6
71 | 1 | 0.4
72 | 1 | 0.4
73 | 1 | 0.4
75 | 8 | 3.1
76 | 3 | 1.2
77 | 3 | 1.2
78 | 3 | 1.2
79 | 3 | 1.2
80 | 8 | 3.1
81 | 1 | 0.4
82 | 2 | 0.8
83 | 4 | 1.6
85 | 10 | 3.9
86 | 2 | 0.8
87 | 1 | 0.4
88 | 3 | 1.2
89 | 2 | 0.8
90 | 26 | 10.2
91 | 1 | 0.4
92 | 3 | 1.2
93 | 3 | 1.2
94 | 2 | 0.8
95 | 13 | 5.1
96 | 3 | 1.2
97 | 2 | 0.8
98 | 5 | 2.0
99 | 8 | 3.1
100 | 107 | 42.1

This line of code:
```
x <- data$`Recommend`
kable(table(npc(x, breaks = list(0:60, 70:80, 90:100))))
```

gives me this table:

Var1	| Freq
-- | -- 
Detractor | 12
Passive | 44
Promoter | 198

This is the table I want, but it doesn't give me percentages. I want to use my tally_and_percent function to give me the percent NPS along with the count. Any ideas?

[Here](https://github.com/carpentries/assessment/blob/master/learner-assessment/data-carpentry/postworkshop/2018-January/2018-January-post.Rmd) is the code.

**Comment by ha0ye** [comment]
Try
```
data$`Recommend` %>%
    npc(breaks = list(0:60, 70:80, 90:100)) %>%
    data.frame(category = .) %>%
    filter(!is.na(category)) %>%
    count(category) %>%
    mutate("%" = n / sum(n)) %>%
    kable()
```

Note I had to filtered out the NA values, so that the remaining percentages would sum to 1, but you can adjust that if needed.

**Comment by kariljordan** [comment]
Thank you @ha0ye!!! THIS DID THE TRICK!

**Comment by tracykteal** [comment]
Thanks! The breakdown for 'promoter', 'passive' and 'detractor' is a great way to represent this data.
