### ISSUE TITLE
Mailing list sign up in README

### ISSUE THREAD

**Issue by jduckles** [carpentries/assessment#140]
@kariljordan Do you think having  this repo's read `README.md` have some resources/guides for getting involved in the assessment network would work? I'm often looking to point people to the Assessment network and I don't have a link to share to help the feel invited and get started.

**Comment by kariljordan** [comment]
Hi @jduckles, you'd like me to add "how to get involved with the assessment network" info to the main [assessment READme.MD](https://github.com/carpentries/assessment/blob/master/README.md)? Or to the [assessment-network README.md](https://github.com/carpentries/assessment/blob/master/assessment-network/README.md)?

**Comment by kariljordan** [comment]
[PR](https://github.com/carpentries/assessment/pull/143) that may help.

**Comment by kariljordan** [comment]
@tracykteal is doing QA on the assessment repo and will offer more recommendations to improve it, so I'm going to close this issue.
