### ISSUE TITLE
link to reports in dc postworkshop learner assessment 404s

### ISSUE THREAD

**Issue by tracykteal** [carpentries/assessment#141]
The link to the reports on the README page in assessment/learner-assessment/data-carpentry/postworkshop/ needs to be updated.

Right now it links to something that isn't there, so 404s

**Comment by kariljordan** [comment]
[Links](https://github.com/carpentries/assessment/blob/master/learner-assessment/data-carpentry/postworkshop/README.md) are correct now. Thank you for catching that!
