### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tracykteal** [carpentries/assessment#148]
We need licenses in this repo. Can we have one license for everything in this repo? Is it all the same? Data, code and reports? I think everything should be abel to be CC-BY, but @kariljordan can you check on that.

**Comment by kariljordan** [comment]
GitHub has a list of [open source licenses](https://blog.github.com/2013-07-15-choosing-an-open-source-license/). I read through them and used [choose a license](https://choosealicense.com) and chose to go with the [MIT License](https://choosealicense.com/licenses/mit/). Let me know if you have objections to this. [Here](https://github.com/carpentries/assessment/pull/161) is the PR.
