### ISSUE TITLE
folder names

### ISSUE THREAD

**Issue by tracykteal** [carpentries/assessment#149]
I know we have 'learner-assessment' and 'programmatic-assessment'. When we have instructor training assessment, where will that go? Also, where will people naturally look for things? I know you've already changed folder names around, so this is for consideration, not necessarily a 'to do'. 

What about
- workshop-assessment
- instructor-training-assessment
- programmatic-assessment

Are there other types of assessment that we're planning or could anticipate? What about assessment of the mentoring programming, or member organizations. Would it fit this scheme?

**Comment by kariljordan** [comment]
Instructor training assessment is in the programmatic-assessment folder [here](https://github.com/carpentries/assessment/tree/master/programmatic-assessment). Instructor training is a "program" in my opinion. Assessment for mentoring would also go in the programmatic-assessment folder. If we're considering assessment of member organizations it would either be with respect to learners or instructor training, so the same folders would apply. Let me know if that's ok.
