### ISSUE TITLE
README in assessment/learner-assessment/data-carpentry/preworkshop/

### ISSUE THREAD

**Issue by tracykteal** [carpentries/assessment#150]
README in assessment/learner-assessment/data-carpentry/preworkshop/ says "As of 2017-10-13, the content in this folder needs to be updated." Is that still correct?

**Comment by tracykteal** [comment]
This README in general needs to be updated maybe?

**Comment by kariljordan** [comment]
Here is the [PR](https://github.com/carpentries/assessment/pull/162)
