### ISSUE TITLE
Main README

### ISSUE THREAD

**Issue by tracykteal** [carpentries/assessment#151]
The main README is much improved, but there's maybe still a bit too much about the learner assessment rather than an overall description of the repo. 

Maybe something like this as the intro, but also include some of your general text that's there too.

This repository contains the assessment data, analysis code and reports for The Carpentries.

The Carpentries teach core computational and data skills to researchers and train instructors to teach workshops and computational skills. We value a culture of assessment and consistently assess learner outcomes from workshops (short and long term) and other programmatic efforts. 

All of the data, code and reports in this repository are publicly available under the  ... license. 

This repository includes assessment of

- [workshops](https://github.com/carpentries/assessment/tree/master/learner-assessment)
- [other programmatic efforts](https://github.com/carpentries/assessment/tree/master/programmatic-assessment)

We also support an [assessment-network](https://github.com/carpentries/assessment/tree/master/assessment-network) that collaborates and shares resources on assessment within the open source/research computing space.

**Comment by kariljordan** [comment]
Updated in [this PR](https://github.com/carpentries/assessment/pull/163)
