### ISSUE TITLE
README in assessment/learner-assessment/data-carpentry/postworkshop/

### ISSUE THREAD

**Issue by tracykteal** [carpentries/assessment#152]
This README also needs some updating. If I'm coming to this repo, what is it that I should be paying attention to, and for what?

Also aren't pre and post analysis now combined, because they're paired? So, where should I be looking for the reports? It seems likely that it's here, but this does get a bit more confusing with this format.

**Comment by kariljordan** [comment]
Paired analyses will go in the post-workshop folder. I updated the README in [this PR](https://github.com/carpentries/assessment/pull/164)
