### ISSUE TITLE
Data Carpentry post-workshop report

### ISSUE THREAD

**Issue by tracykteal** [carpentries/assessment#155]
Reviewing the Data Carpentry post-workshop survey report
https://carpentries.github.io/assessment/learner-assessment/data-carpentry/postworkshop/2018-January/2018-January-post.html

- In tables where things are listed out by category also add 'Total' at the end
- In 'Perception of Workshop Impact', list the descriptive things in the same order as they're in the table below. Also, maybe want to add the label used in the figure in the description, e.g. RawData: Having access to the original, raw data is important to be able to repeat an analysis.
- Use the same order in both 'Perception of workshop impact' graphs
- Maybe move the 'Accessibility issues' question to the end and comment on it? Or is this more programmatic than learner assessment, so shouldn't be included here? I'll submit a separate issue on this question.
- In 'Evaluation of Instructors' use the same order in both figures
- In 'Recommending' it says "Those who respond with a score of 90 to 100 are called Promoters, and are considered likely to recommend a workshop. Respondents between 70 and 80 are labeled Passives, and their behavior falls in the middle of Promoters and Detractors." What are the people in the 80-90 category? Are they included in the numbers in the 'Detractors, Passive, Promoters' table?
- It just ends with the last question. I'm not sure what to add at the end that would be something that would be easy to automate, but maybe again a quick recap, e.g. This is survey results data from ... to .... These reports are updated monthly and available in this repo..

**Comment by tracykteal** [comment]
Not all the 'perception of workshop impact' questions are paired. It looks like just 6 are. In that table can we separate out the ones that are paired and the ones that aren't?

For instance, it would be nice to have a figure that just included the
- I can immediately apply what I learned
- I felt comfortable learning in this workshop environment

**Comment by tracykteal** [comment]
It looks like the question "Using a programming language like R or Python can make me more efficient at working with data" isn't paired. Should it be? It seems like something that would be good to have a comparison pre and post.

**Comment by kariljordan** [comment]
Adding a task list
- [ ] In tables where things are listed out by category also add 'Total' at the end
- [ ] In 'Perception of Workshop Impact', list the descriptive things in the same order as they're in the table below. Also, maybe want to add the label used in the figure in the description, e.g. RawData: Having access to the original, raw data is important to be able to repeat an analysis.
- [ ] Use the same order in both 'Perception of workshop impact' graphs
- [ ] Maybe move the 'Accessibility issues' question to the end and comment on it? Or is this more programmatic than learner assessment, so shouldn't be included here? I'll submit a separate issue on this question.
- [ ] In 'Evaluation of Instructors' use the same order in both figures
- [ ] In 'Recommending' it says "Those who respond with a score of 90 to 100 are called Promoters, and are considered likely to recommend a workshop. Respondents between 70 and 80 are labeled Passives, and their behavior falls in the middle of Promoters and Detractors." What are the people in the 80-90 category? Are they included in the numbers in the 'Detractors, Passive, Promoters' table?
- [ ] It just ends with the last question. I'm not sure what to add at the end that would be something that would be easy to automate, but maybe again a quick recap, e.g. This is survey results data from ... to .... These reports are updated monthly and available in this repo..
- [ ] It looks like the question "Using a programming language like R or Python can make me more efficient at working with data" isn't paired. Should it be? It seems like something that would be good to have a comparison pre and post.
- [ ] Not all the 'perception of workshop impact' questions are paired. It looks like just 6 are. In that table can we separate out the ones that are paired and the ones that aren't? For instance, it would be nice to have a figure that just included the
     - [ ] I can immediately apply what I learned
     - [ ] I felt comfortable learning in this workshop environment

**Comment by kariljordan** [comment]
I removed the Likert figure for perception of workshop impact and left the heat map. I ordered the bullets as they are in the heat map and added axis labels. See [here](https://github.com/carpentries/assessment/commit/a81668bfc972036c275a6715be34309566a4adf6)

**Comment by kariljordan** [comment]
Added summary of accessibility issues [here](https://github.com/carpentries/assessment/commit/69209a7bc0af42fc6289ed320d1dc936e081e009)

**Comment by kariljordan** [comment]
Removed Likert plot for perception of instructors. We don't need both. See [here](https://github.com/carpentries/assessment/commit/2208c9792851758cf8df4cfc5c181c688f2b16f1).

**Comment by kariljordan** [comment]
Per the [NPS calculation](https://www.netpromoter.com/know/)

- Promoters (score 9-10) are loyal enthusiasts who will keep buying and refer others, fueling growth.
- Passives (score 7-8) are satisfied but unenthusiastic customers who are vulnerable to competitive offerings.
- Detractors (score 0-6) are unhappy customers who can damage your brand and impede growth through negative word-of-mouth.

We use 0-100 so I'm assuming it's really scores of 0-69 (detractors), 70-89 (passives), and 90-100 (promoters). Does that make sense @tracykteal? If so I can change the numbers to those in the report.

**Comment by kariljordan** [comment]
Added summary/contact info [here](https://github.com/carpentries/assessment/commit/acc601e0c115775388c657ad6712072500d4f044).

**Comment by kariljordan** [comment]
This question:
> Using a programming language like R or Python can make me more efficient at working with data" isn't paired
>
Has been added to the pre-workshop survey so that it can be paired.

**Comment by kariljordan** [comment]
I archived the data as of today and added it to the [private data repo](https://github.com/carpentries/private-data/commit/0f0e72bf1d8eb9cfd34212a12d61bcc541b225c5). This is because when I delete the two questions from the paired data matrix it will remove the corresponding data. I moved the two questions and made them their own questions so that we can have separate figures for them un-tied to the paired data questions. See [here](https://github.com/carpentries/assessment/commit/c45b820a8d6add3da56866dfde54be1f46053c86).

**Comment by kariljordan** [comment]
@tracykteal the only issue I haven't addressed in this list of issues is adding a row of column totals to all the tables. @fmichonneau mentioned that doing this with kable() is complicated, and that I can use xtable() instead. I've looked into that and also addmargins, but haven't found the solution yet. I will come back to it.

**Comment by tracykteal** [comment]
For the NPS, it seems like rounding up or down could be most consistent with the 1-10 scale. If someone selected 89, they would have been more likely to select 9 rather than 8 if they had a 1-10 scale. So that would make it 0-64 (detractors) 65-84 (passive) 85-100 (promoters). What do you think?

**Comment by tracykteal** [comment]
OK on not adding the totals. It's not necessary, just an extra.

**Comment by tracykteal** [comment]
Does updating the paired data matrix to exclude those questions mean that we can't include the past survey data, before that change, in our reports?

**Comment by kariljordan** [comment]
I'll change the language in the report for the NPS. Rounding is a great idea. I do want to figure out how to add totals in tables, so I'm still going to ask around. Updating the paired data matrix doesn't mean we can't include past data. I'm actually working on the report with the past data now. See [here](https://carpentries.github.io/assessment/learner-assessment/data-carpentry/postworkshop/2018-March/180118_paired_analysis.html). As long as we have the data I can always merge the datasets.

**Comment by tracykteal** [comment]
Great about being able to use past data! It looks like the 'I can immediately apply what I learned' questions aren't in the current report. Is that just a part of the update?

**Comment by kariljordan** [comment]
I just started the current report last night. I haven't added the immediately apply question yet. I was working on the pre/post comparison first because that's what you need for your talk:)
