### ISSUE TITLE
Accessibility data

### ISSUE THREAD

**Issue by tracykteal** [carpentries/assessment#156]
In the Data Carpentry post workshop report, it says that 11% of people have an accessibility issue that impacts their engagement in the workshop. This is important for us to know. Can we look at the free response data for that question to see what the issues are?

**Comment by kariljordan** [comment]
This was addressed in the [updated report](https://carpentries.github.io/assessment/learner-assessment/data-carpentry/postworkshop/2018-January/2018-January-post.html)
