### ISSUE TITLE
Free response data on survey reports

### ISSUE THREAD

**Issue by tracykteal** [carpentries/assessment#157]
In the regular reports for assessment, we're focusing on the numerical data. We're also getting a lot of free-text responses. Raw free text response data can't be made publicly available via IRB, but is there a way we can use this data to aggregate responses and include it in reports, or a separate report?

**Comment by kariljordan** [comment]
I added a task in Asana to add free-response data to all of our reports. The hold-up thus far is that I wanted to use an R package to analyze this data. Given the time it takes me to learn things in R, I will just read the free responses and summarize them moving forward until I have time to work on a workflow that includes analyzing the free responses in R.
