### ISSUE TITLE
perception of workshop impact - paired

### ISSUE THREAD

**Issue by tracykteal** [carpentries/assessment#158]
I know the 'perception of workshop impact' data is paired pre and post. How is this working in the reporting? Is the data currently in the report just from the post-workshop survey? If so, how do those numbers compare with the 'before the workshop' numbers?

**Comment by kariljordan** [comment]
The script @ErinBecker and I worked on to merge the paired data has been added to the repo [here](https://github.com/carpentries/assessment/commit/a8dfb065f86dbd52d315f47ec15427a56e51baae). I've added a task to my Asana to work on the report for the paired data.
