### ISSUE TITLE
Ordering in Perception of workshop impact

### ISSUE THREAD

**Issue by tracykteal** [carpentries/assessment#165]
We look at if people think what they learned will make them more efficient and that they understand how the skills can help with reproducibility, and we also look at self-efficacy. We could order the things in Perception of workshop impact by these clusters

Efficiency
- Write Programming
- Confidence Software

Reproducibility
- Raw data
- Programming easier

Self-efficacy
- Technical questions
- Overcome problems
- Confident programming

**Comment by kariljordan** [comment]
@fmichonneau @tracykteal keep this in mind once the new script is written
