### ISSUE TITLE
Specific software questions for type of Data Carpentry workshop being held

### ISSUE THREAD

**Issue by angela-li** [carpentries/assessment#17]
I'm curious as to if it would be possible to customize the "Software Previously Used" question to include software specific to the workshop being taught, if the workshop is a Data Carpentry one.

For example, as an instructor teaching the Geospatial Workshop, it's very important for me to know if my students have used ArcGIS/QGIS before, which is a point-and-click GIS software. This helps me structure my curriculum to account for my learners' needs.

I realize this might not be the goal of this assessment, so feel free to let me know it's not. Perhaps this can be solved by including an option in Q8 ("How often do you currently use any of the following?) for "Specialized disciplinary software with a point and click interface (ArcGIS, OpenRefine, etc)"?

**Comment by kariljordan** [comment]
Hi @angela-li, I really like the way you've phrased: _Specialized disciplinary software with a point and click interface (ArcGIS, OpenRefine, etc)_. We look at the surveys quarterly to make sure we're asking the right questions to get the data we need. I made a note to myself to come back to this question at the end of the year. Thanks so much!

**Comment by fmichonneau** [comment]
Thanks for the suggestion Angela. The question now reads:

> A specialized software with a point-and-click graphical user interface (e.g., for statistical analysis: SPSS, SAS, ...; for Geospatial analysis: ArcGIS, QGIS, ... ; for Genomics analysis: Geneious, ...)

**Comment by angela-li** [comment]
Thank you for including this question! I look forward to reviewing this survey question the next time I teach the Social Science or Geospatial curricula.
