### ISSUE TITLE
Render output to specific path

### ISSUE THREAD

**Issue by kariljordan** [carpentries/assessment#170]
I want the RMD files to go in the code folder, and the rendered PDF to go in the reports folder. How do I set opts_chunk$set to accomplish this? Also, should the HTML file go in the code folder or the documents folder?

**Comment by kariljordan** [comment]
@fmichonneau ideas are appreciated!

**Comment by fmichonneau** [comment]
It's now set up such that the source for the reports (the .Rmd files) will live in `reports-src/` and the outputs will live in `reports/`. We can add/edit the `build_reports.R` script to make it easier to get the paths right.
