### ISSUE TITLE
Show progress bar in SurveyMonkey survey

### ISSUE THREAD

**Issue by angela-li** [carpentries/assessment#18]
I think it would encourage learners to fill out the survey if they could see how long it is or a progress bar in the survey. I've noticed people at my workshops clicking out of the survey at the last minute, when they're close to being done, since they're unsure how much longer it will take.

Just a thought!

**Comment by kariljordan** [comment]
Great idea @angela-li. We've transitioned our pre and post workshop surveys from SurveyMonkey to Typeform.

[Here is the announcement](https://carpentries.org/blog/2019/10/transition-to-typeform/).

Check out the [preview](https://carpentries.typeform.com/to/wi32rS) and let us know what you think. Is this an improvement?

**Comment by kariljordan** [comment]
Hi @angela-li, checking to see what you thought about the new survey.
