### ISSUE TITLE
Add jitter to attendance scatterplot

### ISSUE THREAD

**Issue by maneesha** [carpentries/assessment#182]
The attendance scatterplot the density of frequency of attendance rates in the middle of the range.  How do we add a jitter to this?

**Comment by ErinBecker** [comment]
This adds a boxplot to the attendance rate data:

`attendance.boxplot(column='attendance', by='year')`

**Comment by ErinBecker** [comment]
These two lines do the same for the instructor training data:

`badges_by_training_event['year'] = badges_by_training_event['start'].dt.year
badges_by_training_event.boxplot(column = 'attendance', by = 'year')`

**Comment by ErinBecker** [comment]
This shows percent completion of instructor training by year: 

`badges_by_training_event.boxplot(column = 'pct_completion', by = 'year')`

**Comment by ErinBecker** [comment]
And this shows percent completion of instructor training vs attendance 

`badges_by_training_event.plot.scatter('attendance', 'pct_completion')`

**Comment by ErinBecker** [comment]
![screen shot 2018-05-14 at 3 45 23 pm](https://user-images.githubusercontent.com/19176319/40027619-c23c579c-578f-11e8-8281-b874d5efa2e7.png)
![screen shot 2018-05-14 at 3 58 41 pm](https://user-images.githubusercontent.com/19176319/40027620-c3342b34-578f-11e8-9b4b-f1db9805b3d0.png)
![screen shot 2018-05-14 at 3 58 52 pm](https://user-images.githubusercontent.com/19176319/40027623-c489aaf4-578f-11e8-928e-6e56875fc50d.png)

![screen shot 2018-05-14 at 3 58 57 pm](https://user-images.githubusercontent.com/19176319/40027626-c7b616d6-578f-11e8-950d-5f62ea65b60d.png)

**Comment by ErinBecker** [comment]
![screen shot 2018-05-14 at 3 59 02 pm](https://user-images.githubusercontent.com/19176319/40027681-ffaf8fa4-578f-11e8-8679-72530ec4c9da.png)

**Comment by maneesha** [comment]
closing this - replaced scatter plot with box plot
