### ISSUE TITLE
Sort table by index of mixed types

### ISSUE THREAD

**Issue by maneesha** [carpentries/assessment#185]
The table showing how many countries had their first workshop each year has an index of mixed types (ints for each year, plus string 2018Q1).  How do we sort this by year?

**Comment by maneesha** [comment]
Solved for now by marking all years as ints and noting 2018 is a projection in the narrative/caption.  Still would like to know the best way to do this.

**Comment by fmichonneau** [comment]
This issue was moved to fmichonneau/assessment-new#5
