### ISSUE TITLE
Add total rows to tables

### ISSUE THREAD

**Issue by maneesha** [carpentries/assessment#188]
There are many tables that show workshops by year, by country, etc.  Total columns have been added to these tables.  Would be good to have a total row as well.

**Comment by grahamalama** [comment]
I wanted to make a `pivot_table` and use `[margins=True](https://pandas.pydata.org/pandas-docs/stable/reshaping.html#adding-margins)`, but I got an error, `'Series' objects are mutable, thus they cannot be hashed`. 

Instead, I made wrote this simple function that works as long as long as both the rows and columns are only one 'level' deep: 
```python
def append_totals(df):
    df['total'] = df.sum(axis=1)
    return df.append(df.sum().rename('total'))
```

So for something like the table `workshops_by_country_year`, remove 
```python
workshops_by_country_year['total'] = workshops_by_country_year.sum(axis=1)
``` 
and when the table is 'ready', call `append_totals(workshops_by_country_year)` which will return the dataframe with the total rows.

**Comment by maneesha** [comment]
This looks great @grahamalama !  I've changed a bunch of tables since I originally posted this issue but am going to try to incorporate your function into them and see how it looks.

**Comment by maneesha** [comment]
Changes incorporated into this version of notebook 526f86b34a46fdb 
Thanks again @grahamalama
