### ISSUE TITLE
flip order of legend items in barh chart

### ISSUE THREAD

**Issue by maneesha** [carpentries/assessment#198]
We have a horizontal bar chart of all countries that ran at least 10 workshops 2012-2018.
Each country has a bar for each year, with the bars ascending chronologically down the chart.  The legend has the correct color codes but in reverse order.  How do you reverse the order of the legend items?

See
![image](https://user-images.githubusercontent.com/829690/40131683-a3565d12-5908-11e8-9f80-7b8e7577449e.png)

**Comment by tbekolay** [comment]
According to a [StackOverflow thread](https://stackoverflow.com/questions/34576059/reverse-the-order-of-legend), you can do it with this, in lieu of the normal `plt.legend` call:

```python
handles, labels = ax.get_legend_handles_labels()
ax.legend(handles[::-1], labels[::-1], title='Line', loc='upper left')
```

The only issue would be if you already have the legend plotted, as you don't want two overlapping legends. If there is a legend already plotted, I believe you can [remove it](https://stackoverflow.com/questions/5735208/remove-the-legend-on-a-matplotlib-figure) like so:

```python
ax.legend().remove()
```

These lines should work regardless of how the plot is created. If you're making the plot manually (without Seaborn or Pandas or what have you) then there are likely easier ways to fix the legend ordering. But my guess is you're using Pandas!

**Comment by maneesha** [comment]
Thanks @tbekolay  I will try this out.  (Yes, it's all in Pandas)

**Comment by maneesha** [comment]
This worked perfectly! Thanks @tbekolay
