### ISSUE TITLE
tables don't render well when publishing to pdf via nbconvert

### ISSUE THREAD

**Issue by maneesha** [carpentries/assessment#199]
See:

https://github.com/carpentries/assessment/blob/master/programmatic-assessment/workshops/outputs/sample_report.pdf

Table formatting gets thrown off.

Tables do render well in html:

http://htmlpreview.github.io/?https://github.com/carpentries/assessment/blob/master/programmatic-assessment/workshops/outputs/sample_report.html

**Comment by tbekolay** [comment]
Any chance you could include the `.tex` file that produces the `.pdf`? That should make it obvious why the table is misformatted.

**Comment by rgaiacs** [comment]
@maneesha Could you break the notebook in a minimal example? It always helps to track the problem down.

**Comment by maneesha** [comment]
@rgaiacs Check out the [test_mini](https://github.com/carpentries/assessment/blob/test_notebook/programmatic-assessment/workshops/test_mini.ipynb)  notebook in the   [test_notebook branch](https://github.com/carpentries/assessment/tree/test_notebook/programmatic-assessment/workshops)

The corresponding html and pdf outputs are in the [outputs](https://github.com/carpentries/assessment/tree/test_notebook/programmatic-assessment/workshops/outputs) folder. The markdown table doesn't seem to get squished, but the pandas df table still does not show in the pdf.

**Comment by maneesha** [comment]
Workaround - I've been printing the html to pdf in my browser.  Keeping this issue open in case anyone has other suggestions.

**Comment by fmichonneau** [comment]
This issue was moved to fmichonneau/assessment-new#2
