### ISSUE TITLE
Better way to do attendance projections?

### ISSUE THREAD

**Issue by maneesha** [carpentries/assessment#201]
For projections of number workshops for 2018, I took the proportion of 2017 workshops run in 2017 Q1 and applied it to the 2018 Q1 workshop count.  This includes country specific and carpentry specific projections (so 2018 projections for USA workshops are based on 2017 USA data).

For now, the same thing is done for attendance data.  The proportion of 2017 attendees who came in 2017 Q1 was applied to the number of attendees we saw in 2018 Q1.

The attendance projection for 2018 does not directly account for the number of workshops or class size.  Should we do this?  If so how do we do this?

**Comment by fmichonneau** [comment]
This issue was moved to fmichonneau/assessment-new#6
