### ISSUE TITLE
Visualizing sustainability of workshops in each country

### ISSUE THREAD

**Issue by maneesha** [carpentries/assessment#203]
We have a map that shows for each country that has ever hosted a Carpentries workshop, what year their first workshop was in.

For next report I would like to show sustainability - how many countries are "one and done" and how many have hosted at least one workshop a year since their first year.  Ideas on how to visualize this are welcome.

Sample current graphics (data may change):

**Year each country hosted first workshop:**

![image](https://user-images.githubusercontent.com/829690/41166861-4b0bfacc-6b0f-11e8-9344-c77cecfa0b34.png)

**Workshops by year for most active countries**
![image](https://user-images.githubusercontent.com/829690/41166897-63fb33f4-6b0f-11e8-913f-c36c00d42b47.png)

**Comment by fmichonneau** [comment]
This issue was moved to fmichonneau/assessment-new#3
