### ISSUE TITLE
Moving to common survey

### ISSUE THREAD

**Issue by kariljordan** [carpentries/assessment#211]
I am beginning this thread to discuss moving to a common pre/post workshop survey that will be used across all of the Carpentries.

@libcce would like to add this question to the LC survey. 

> Which of the following lessons did you cover in your workshop?
o Data Intro
o Data Intro for Archivists
o Regular Expressions/GREL
o Unix Shell
o Open Refine
o Git
o SQL
o Python
o Tidy Data
o Web scraping

> 
It should be rephrased to say: Which of the following skills were covered in your workshop? 

If we applied this question to all of the surveys we'd have to list out every skill from all of the learning objectives. Not a fan of that.

The original question is: 

> Which of the following programming languages was covered in your workshop?

- R
- Python
- Neither
- I don't know./I don't remember.

**Comment by libcce** [comment]
@kariljordan There is a more generic question we use which lists options by headings such as databases, programming languages, versioning, etc. and lists examples next to the headings. This might be a better approach?

**Comment by kariljordan** [comment]
I am closing this issue as we are currently working on this project and everyone's feedback has been incorporated.
