### ISSUE TITLE
Considered slope charts to compare pre- & post-workshop data or other time series?

### ISSUE THREAD

**Issue by katrinleinweber** [carpentries/assessment#215]
Hello :-)

I would like to try converting one or the other plot into a [slope chart/graph](http://charliepark.org/slopegraphs/). For example: https://github.com/carpentries/assessment/blame/master/learner-assessment/reports-src/2018-07-learners-pre-post-surveys.Rmd#L1066-L1103

Do you have any comments about whether or not a slope chart/graph would be useful or feasible in the reports? Any objections against such a PR?

If not, please feel free to assign the issue to me. I'm starting a [local study group](https://github.com/TIBHannover/2018-07-09-FAIR-Data-and-Software/pull/12), for which that may be a neat datavis example.

Thanks!

**Comment by kariljordan** [comment]
Hi @katrinleinweber! Would you mind trying it out on [this report](https://github.com/carpentries/assessment/blob/master/learner-assessment/code/2018_July_longterm_impact.Rmd)? I'd love to see how it looks, and then move forward with changing the other report as well. This is such a great idea!

**Comment by katrinleinweber** [comment]
I have some code ready for `2018-07-learners-pre-post-surveys.Rmd` as well. I'll include it in #218 once we have agreed on the first example and thus the `slopegraph_theme()`.
