### ISSUE TITLE
2020 Long Term Assessment Report - omission of "Became a Carpentry Instructor" in "Involvement in Carpentries Community Post-Workshop" figure 

### ISSUE THREAD

**Issue by npch** [carpentries/assessment#22]
In the [analysis report](https://carpentries.github.io/assessment/learner-assessment/reports/2020-01-long-term-report.html), the figure showing the different options for "Involvement in Carpentries Community Post-Workshop" is missing the category of "Became a Carpentry Instructor", which is in the raw data.

Thank you for producing this report - it's so useful for us to show the ongoing benefit of Carpentries to funders and stakeholders. 👍

**Comment by fmichonneau** [comment]
thank you so much for pointing this out!
