### ISSUE TITLE
Add github.io link to description and assignees

### ISSUE THREAD

**Issue by kariljordan** [carpentries/assessment#24]
Can we add the link below to the area at the top of the repo that's meant for descriptions, links, etc?

https://carpentries.github.io/assessment/

Also, I wanted to assign an issue to @karenword and Kelly Barnes but was not able to. Do they have access to this repo?

**Comment by fmichonneau** [comment]
I added the link in the Description.
As for access, we had limited who had write access to this repo after the [potential data leak](https://carpentries.org/blog/2018/10/survey-data/). If we start adding more people I'd like to enable branch protection.

**Comment by maneesha** [comment]
I see @fmichonneau added in the link; I added in the sentence description as well.

Re-assigning to François to address the branch protection concern.

**Comment by kariljordan** [comment]
Thank you both! If we can enable branch protection that would be great. This is not a priority at this moment, but I would like @karenword to be able to update this repo as she'll be leading a lot of our assessment efforts moving forward.

**Comment by fmichonneau** [comment]
branch protection was already enabled, I'm adding @karenword to have write access the repo.
