### ISSUE TITLE
Visualizing sustainability of workshops in each country

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/assessment#3]
_From @maneesha on June 8, 2018 15:31_

We have a map that shows for each country that has ever hosted a Carpentries workshop, what year their first workshop was in.

For next report I would like to show sustainability - how many countries are "one and done" and how many have hosted at least one workshop a year since their first year.  Ideas on how to visualize this are welcome.

Sample current graphics (data may change):

**Year each country hosted first workshop:**

![image](https://user-images.githubusercontent.com/829690/41166861-4b0bfacc-6b0f-11e8-9344-c77cecfa0b34.png)

**Workshops by year for most active countries**
![image](https://user-images.githubusercontent.com/829690/41166897-63fb33f4-6b0f-11e8-913f-c36c00d42b47.png)

_Copied from original issue: carpentries/assessment#203_

**Comment by unode** [comment]
Hi François

Is there an updated figure of "Workshops by year for most active countries" including numbers from 2019 available somewhere?
Alternatively, does https://carpentries.org/past_workshops/ exist in CSV or other convenient downloadable formats?

Thanks

**Comment by maneesha** [comment]
@unode You can check out our data feeds here https://feeds.carpentries.org/
which should give you the information you are looking for.

**Comment by unode** [comment]
@maneesha Awesome! Thanks!
